#!/bin/bash
set -ux -o pipefail 

# oracle download java page: https://www.oracle.com/java/technologies/javase-jdk16-downloads.html

bm=0
#Ubuntu
sudo apt update
sudo apt upgrade -y
apt dist-upgrade
sudo apt autoremove

#Chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P /tmp
sudo sudo apt install /tmp/google-chrome-stable_current_amd64.deb

sudo apt install -y wireguard vim htop zip unzip sysstat screen openvpn nfs-common git tig meld chrome-gnome-shell \
default-jdk python2 gnome-tweaks dconf-editor sshfs pigz python3-venv cachefilesd clamav clamav-daemon

gsettings set org.gnome.shell.extensions.dash-to-dock isolate-workspaces true
gsettings set org.gnome.shell.extensions.dash-to-dock isolate-monitors true
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left "['<Primary><Shift><Alt>Left']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right "['<Primary><Shift><Alt>Right']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "['<Primary><Shift><Alt>Up']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "['<Primary><Shift><Alt>Down']"
#gsettings list-recursively org.gnome.desktop.wm.keybindings

sudo sed 's/#RUN=yes/RUN=yes/' -i /etc/default/cachefilesd 
sudo systemctl enable --now cachefilesd # nfs -o fsc, sshfs cache=yes

#Firefox - the snap just stopped working
sudo snap remove firefox
sudo add-apt-repository ppa:mozillateam/ppa
echo '
Package: *
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 1001
' | sudo tee /etc/apt/preferences.d/mozilla-firefox
echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox
sudo apt install firefox -y

mkdir ~/.local/bin
echo '
#!/bin/bash
swapfile=/swapfile
sudo truncate -s 0 ${swapfile}
sudo chattr +C ${swapfile}
sudo fallocate -l 2G ${swapfile}
suso chmod 0600 ${swapfile}
sudo mkswap ${swapfile}
sudo swapon ${swapfile}
' | tee ~/.local/bin/reset-swap
chmod +x ~/.local/bin/reset-swap

echo "pkill chrome" > ~/.bash_logout

[ ${bm:-0} -eq 1 ] || exit 0

#System utils
sudo apt install -y numactl numad
# sudo apt install virt-manager
# virsh net-autostart default
# xfsprogs mdadm lvm2 virtualbox

# https://gist.github.com/the-spyke/2de98b22ff4f978ebf0650c90e82027e
sudo apt install pipewire-media-session- wireplumber
systemctl --user --now enable wireplumber.service
sudo apt install pipewire-audio-client-libraries
sudo cp /usr/share/doc/pipewire/examples/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d/
sudo apt install libldacbt-{abr,enc}2 libspa-0.2-bluetooth pulseaudio-module-bluetooth-

# reboot
# Check if working :
# LANG=C pactl info | grep '^Server Name'

# after setting up screens
sudo cp ~/.config/monitors.xml /var/lib/gdm3/.config/


sudo apt install snapper snapper-gui
sudo snapper -c root create-config /
sudo snapper -c home create-config /home
function update_kv {
  sudo sed -n "/$1=/I{{s/\([^=]*=\).*/\1\"$2\"/};p}" -i $3
}
for f in /etc/snapper/configs/root /etc/snapper/configs/home; do
update_kv TIMELINE_LIMIT_HOURLY 5 $f
update_kv TIMELINE_LIMIT_DAILY 7 $f
update_kv TIMELINE_LIMIT_WEEKLY 2 $f
update_kv TIMELINE_LIMIT_MONTHLY 1 $f
update_kv TIMELINE_LIMIT_YEARLY 0 $f
done
sudo systemctl enable --now snapper-timeline.timer
sudo systemctl enable --now snapper-cleanup.timer

exit 0

# gnome extensions
https://extensions.gnome.org/extension/906/sound-output-device-chooser/
https://extensions.gnome.org/extension/1485/workspace-matrix/




https://www.sophos.com/en-us/products/free-tools/sophos-antivirus-for-linux.aspx

Remina: 
https://kbdlayout.info/kbdusx/virtualkeys
Preferences->RDP
0x3a=0x1D,0x1D=0x3a
