#!/bin/bash
set -ux -o pipefail 

bm=0
#Ubuntu
sudo apt-get update
sudo apt-get upgrade -y

sudo apt install -y vim htop zip unzip sysstat screen openvpn nfs-client git tig meld default-jdk python2

#Chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P /tmp
sudo sudo apt install /tmp/google-chrome-stable_current_amd64.deb

[ ${bm:-0} -eq 1 ] || exit 0

#System utils
sudo apt-get install -y xfsprogs mdadm numactl lvm2 virtualbox

https://www.sophos.com/en-us/products/free-tools/sophos-antivirus-for-linux.aspx

exit 0
